import {} from '../../libs/sidebar.js';
import { setherocolorccc } from '../../libs/colors.js';
import { OWNINGTYPE } from '../../libs/colorsname.js';
import {bitget,bitflip } from '../../libs/bitlist.js';
import { addCookie,getCookielist} from '../../libs/cookies.js';

document.addEventListener ("DOMContentLoaded", handleDocumentLoad);

const objdata={"All":[],
    "insignias":[
"Brawler's Insignia",
"Founder's Insignia",
"Collector's Insignia",
"Founder's Insignia (PS4)",
"Skyforged Jewel",
"Goldforged Jewel",
"Resonance",
"Cosmic Radiance",
"Roar of the Order",
"XIX. The Sun",
"Fae's Gift",
"Demonic Portal",
"Candlelight's Glow",
"Terminus Street Signs",
"Merciful Death",
"Celestial Dreams",
"Jaguar's Glory",
"Evolution of the Way",
"Age of Dragons",
"Eyes of the Occult",
"RGB Visualizer",
"Helios' Radiance",
"Hardlight Display",
"Team Naughty",
"Team Nice",
"Team Pancakes",
"Team Waffles",
"Team Sweet",
"Team Sour",
"Luck",
"Skill",
"Speed",
"Strength",
"Light",
"Shadow",
"Team Vampires",
"Team Werewolves",
"Scouts",
"Titans",
"Archangel"
],
    "ko effects":[
"Smoke N' Stars",
"Flames of Ragnarok",
"High Score!",
"Party Time",
"Astral Prison",
"Thor's Applause",
"T-Rekt",
"Balefire Wyrm",
"Loki's Grasp",
"Medieval Dragon",
"Rainicorn Rumble",
"Malachite",
"Vilgax",
"Walker's Grasp",
"Master Shifu",
"Enter The Shredder",
"Knockout",
"Desynchronization",
"Cabbage Merchant",
"Grunt Explosion",
"Panda Slam",
"King Jellyfish",
"Mega Man KO",
"Mirage's Fury",
"No Escape",
"Yunyun's Protection",
"KO-Ching!",
"XO KO",
"Hot Lava",
"Frostbite",
"Jac-KO-Lantern",
"Smiling Titan",
"Bite the Dusk",
"Mongo",
"Hellfire",
"Digital Breakdown.wav",
"Nidhogg's Appetite",
"Unchained Resolve",
"Black Hole",
"Flower Food",
"Dice Hoarder",
"Darkheart Metamorphosis",
"Fallout",
"Hana-KO-toba",
"Triumphant Return",
"Shadow Clone",
"Malakkar",
"Divine Encounter"
],
    "trails":[
    "Default",
    "Soul Blast",
    "Echoes of Balance",
    "Fenrir's Eminence",
    "Surt's Wrath",
    "Flames of Muspelheim",
    "Shadow Dragon",
    "Archangel's Arrival"
],
    "emotes":[
"Woohoo!",
"Slow Clap",
"Roof Dance",
"Don't Leave Me Hangin'",
"So Salty",
"Take a Bow",
"The Running Man",
"See Ya!",
"Maniacal Laugh",
"Primal Roar",
"Facepalm",
"Deal With It",
"Thumbs Up!",
"Photo Op",
"Come At Me",
"The Flex",
"Avatar Flag",
"Calculated",
"The Reads",
"Next Level",
"Scissors",
"Paper",
"Rock",
"Shrug",
"Fireworks",
"This Guy",
"Cossack Dance",
"Guitar Solo",
"Blow A Kiss",
"Shadowboxing",
"Smooth Moves",
"Golf Clap",
"Dumbbell Curls",
"Card Shuffling",
"Peace Signs",
"B-ballin'",
"Mourn",
"Faint",
"Robot Dance",
"Nap Time",
"Noooo!",
"Champion's Throne",
"Avatar Cape",
"Burrito Time!",
"Mammoth Ride",
"Snowboarding",
"Brawlcade Cabinet",
"Monitor Smash",
"Kung Footballer",
"Skyforged Trophy",
"Goldforged Trophy",
"Glorified",
"Back to Back",
"Bow to Your Sensei",
"Team Photo",
"Share a Slice",
"Satsui no Hado",
"Leap of Faith",
"Momo",
"Mongoose",
"TEKKEN Arcade Cabinet",
"Bubbles",
"Clarinet",
"Force Levitation",
"Holochess",
"Be A Hero!",
"Brawlhalla Salute",
"Solidarity",
"World Tree Initiative",
"Deep Sea Sightseeing",
"Extra Life",
"Home Team Cheer",
"Skeleton Dance",
"Snowball Juggling",
"Give a Bouquet",
"Pot o' Gold",
"Fly a Kite",
"Werewolf Transformation",
"Beachside Break",
"Surfin'",
"5th Cake-aversary",
"6th Cake-aversary",
"7th Cake-Aversary",
"8th Cake-Aversary",
"9th Cake-Aversary",
"10th Cake-Aversary",
"Handstand",
"Warm Up",
"Push Up",
"RIP",
"Ninja Flip",
"Kung Fu Salute",
"Retro Raver",
"Twinkle Smile",
"Breakdance",
"Keytar Solo",
"Burnout",
"Neon Drive",
"Feast!",
"Lyre Solo",
"Skål",
"Raven",
"Noble End",
"Langskip",
"Gravedigger",
"The Order's Salute",
"Begone Evil",
"Pop an Elixir",
"A Momentary Rest",
"Full Moon's Howl",
"The Order's Lordly Roar",
"Deep Space Laps",
"Wish on a Star",
"UF-OH SNAP",
"Moonwalk",
"Energy of the Universe",
"Stockgazing",
"Blast Off!",
"For Rest",
"Tree Pose",
"Pet the Beetle",
"Faerie Friends",
"Pffftthhhbb!",
"Tree Swing",
"Catching Faeries",
"Luck Check",
"Locked in the Dungeon",
"Treasure Test",
"Lute Solo",
"Spell Circles",
"Skill Check",
"Noble Steed",
"Fist Bump",
"Rock Out!",
"Wall Tag",
"Harness the Darkheart",
"Hoverboard Kickflip",
"Darkheart Power-Up",
"Darkheart Portal",
"Judgement",
"Out of Body Experience",
"Stick Horse",
"LOL RIP",
"Soul Cackle",
"Molten Stallion",
"Lore Accurate Celestial",
"Victory!",
"Ojousama Laugh",
"My Job Here Is Done",
"The Power of Friendship",
"Transformation ☆ Dance",
"Pet the Sidekick",
"The Power of Love",
"Pok-ta-pok",
"Relic of the Lost Temple",
"Heart Sacrifice",
"Summoning Dander",
"Lichlord's Throne",
"Skele-Dance Party",
"Seven Soul Stones",
"Fan Break",
"Ninja Run",
"Ramen Time",
"Substitution Jutsu",
"Dragon's Breath (Emote)",
"Dragon's Hoard",
"Dragon Egg",
"Dragon Ride",
"Random RPS",
"Soul Crush",
"Sweet Taste of Victory",
"Raise Your Vote",
"Sweat",
"Massive W",
"Drum Solo",
"Champion's Belt",
"Legendary Moment",
"Feigning Innocence",
"Check In",
"Enraptured",
"Celestial's Fligth"
],
    "sidekicks":[
"VALKRI Mk 1",
"Cogsworth",
"Zoid",
"Grimm",
"Craig",
"Firehawk",
"Phantom Knight",
"Boomer",
"The Shade",
"Ammit",
"Drake",
"Mammoth Fan",
"Onisan",
"Personal Sentry IV",
"Cheddar",
"Wendigo",
"Mammoth Superfan",
"Mammoth Megafan",
"Forest Dragon",
"Lum King",
"Mammoth Ultrafan",
"Kitsune",
"Blue Oni",
"Ninja",
"Tengu",
"Harlequin Marionette",
"Butterscotch",
"Cyber Fly",
"Techno Pup",
"TV Head",
"Robo-n3k0",
"Mammoth Legionnaire",
"Freya's Chariot",
"Sköll",
"Hati",
"Tanngnjóstr & Tanngrisnir",
"Skyforged Twin-Tailed Ox",
"Goldforged Twin-Tailed Ox",
"Nian Shou",
"Twilly",
"Chimera",
"Living Knight Mare",
"Stone Guardian",
"Harbinger of Souls",
"Mammoth Mystery Fan",
"Mysticetus",
"Delta Cancri",
"Star Miner",
"Zhaktari Minion",
"Sniffles",
"Sal",
"Mandy",
"Ted",
"Razor",
"Bee-Bot",
"Vampire Bat",
"Mammoth Rocketfan",
"Malefic Grasp",
"Appa",
"Drago",
"Goob",
"Tempest",
"Copy Cat (chest form)",
"Terry",
"Banshee",
"BunBun",
"Max",
"Rob",
"Haruto",
"MonoKyle",
"Mammoth Gentle-fan",
"Diablo",
"The Flying Dutchman",
"Miki",
"Dander",
"Kyupi",
"Peckish Pete",
"Mortimer",
"War Horse",
"Plague Rat",
"Molten Terror",
"Kelpie",   
"Kit",
"R2-D2",
"Mammoth Nemesis Superfan",
"Deacon of Rapture",
"Ocean Messenger",
"Hoshi",
"Sol",
"Mecha Legionnaire",
"Fufu",
"Tenma",
"Claptrap",
"Beat",
"Victor",
"Imperial Probe Droid",
"Sam",
"Plush Exalted Lion",
"Plush Valkyrie Mk 1",
"Plush Kitsune",
"Plush Lucy",
"Sekhar, Star Collapser",
"Phil",
"Brioche",
"Sardines",
"Paloma",
"Choco Bun",
"Caiman",
"Ozomatli",
"Xolotl",
"Ocelotl",
"Winged Serpent",
"Dobhar",
"Scarecrow",
"Lucy",
"The Luminary",
"Sandrew",
"Freddie",
"Jinyin",
"Mizuchi",
"Nezumi",
"Kerokero",
"Katakata",
"Kagari",
"Choux",
"Mammoth Free Heart Megafan",
"Bjorn",
"Mac",
"Luminous Leo",
"Precious Pablo",
"Maid of the Stone Mammoth",
"Lil' Helmaw",
"Big Helmaw",
"Lil' Bruce",
"Big Bruce",
"Mulmiho",
"Dandy",
"TermiMart (TM) Limited Edition Aide",
"Jetsam",
"Fenreus",
"Audrey the 3rd",
"Ringo",
"Justice",
"Fortitude",
"Prudence",
"Temperance",
"Archangel",
"Mammoth Spellwitch Fan",
],
    "podiums":[
"Default Podium",
"Heatwave 2017",
"The Upstage",
"Graveyard Shift",
"Winner Wonderland",
"Lion Heart",
"Heatwave 2018",
"Darkheart Spire",
"Toiland Trouble",
"Spellbound Tree",
"Winner Wonderland'18",
"Lovestruck 2019",
"Beast of the Apocalypse",
"Heatwave 2019",
"Graveyard Shift 2019",
"Spirit Temple 1",
"Spirit Temple 2",
"Spirit Temple 3",
"Winner Wonderland'19",
"Lovestruck 2020",
"Tomb Stele",
"Omnitrix",
"Heatwave 2020",
"Arcade Nights 1",
"Arcade Nights 2",
"Arcade Nights 3",
"Days Gone Bye",
"Graveyard Shift 2020",
"Gilded Deco",
"Winner Wonderland'20",
"Lovestruck 2021",
"Yggdrasil's Fate 1",
"Yggdrasil's Fate 2",
"Yggdrasil's Fate 3",
"Floral Bliss 2021",
"Turtle Power",
"Heatwave 2021",
"Fall of the Lions 1",
"Fall of the Lions 2",
"Fall of the Lions 3",
"Ofrenda",
"Gilded Deco 2021",
"Kapukon Yu",
"Winner Wonderland'21",
"Edge of Existence 1",
"Edge of Existence 2",
"Edge of Existence 3",
"Lovestruck 2022",
"Floral Bliss 2022",
"Fabled Overgrowth 1",
"Fabled Overgrowth 2",
"Fabled Overgrowth 3",
"Heatwave 2022",
"Ofrenda 2022",
"Gilded Deco 2022",
"Winner Wonderland'22",
"Hero's Quest 1",
"Hero's Quest 2",
"Hero's Quest 3",
"Lovestruck 2023",
"Floral Bliss 2023",
"Heatwave 2023",
"Darkheart Excavation 1",
"Darkheart Excavation 2",
"Darkheart Excavation 3",
"Ofrenda 2023",
"Gilded Deco 2023",
"Winner Wonderland'23",
"The Truth 1",
"The Truth 2",
"The Truth 3",
"Lovestruck 2024",
"Floral Bliss 2024",
"Heatwave 2024",
"Slice of Life 1",
"Slice of Life 2",
"Slice of Life 3",
"Bespin Carbon Freezing Chamber",
"Ofrenda 2024",
"Gilded Deco 2024",
"Winner Wonderland 2024",
"Lovestruck 2025",
"Fall of Ixanocala 1",
"Fall of Ixanocala 2",
"Fall of Ixanocala 3",
"Floral Bliss 2025",
"Stocksonthe Rocks",
"Millenium Hokora 1",
"Millenium Hokora 2",
"Millenium Hokora 3",
"Haunted Manor",
"Gilded Deco 2025",
"Music Box",
"Sweetheart Haul",
"Fae's Bounty",
"Temple of the Dragonsaint 1",
"Temple of the Dragonsaint 2",
"Temple of the Dragonsaint 3",
"Faerie Grove",
"Lycan Trinity",
"Stocksonthe Rocks'26",
"Protagonist's Desk",
"Stairway to Elysium 1",
"Stairway to Elysium 2",
"Stairway to Elysium 3",
"Haunted Manor 2026",
],
    "companions":[
"Grogu",
"Hunter Ghost",
"Titan Ghost",
"Warlock Ghost",
"Lil' Reaper",
"Star-Drifter Butterscotch",
"Donkey",
"Domo Jr.",
"Murfy",
"Tommy",
],
    "avatars":[],
    "frames":[
"Default Frame",
"Gold Frame",
"Platinum Frame",
"Diamond Frame",
"Valhallan Frame",
"Demon Gate",
"Futurewave",
"Gate to Valhalla",
"Stained Legacy",
"XVI. The Tower",
"Fae's Passage",
"Tavern Entrance",
"Dead End",
"Merciful Life",
"Magical Gateway",
"Ixanocala's Maw",
"Jikoku Nights",
"Dragonportal",
"Portal of Darkness",
"RGB Colorway",
"Luminous Daybreak",
"Hardlight Matrix",
"Divine Gate"
],
    "emojis":{"All":[],
"1More":["1More",
"1More Ashen Warmonger",
"1More Brawl Dad",
"1More Chel",
"1More Dr. Wily",
"1More Erwin",
"1More Gallowglass",
"1More Goldforged",
"1More Guild",
"1More King of Darkness",
"1More Punkin Spice",
"1More Puss in Boots",
"1More Santa",
"1More Secret Admirer",
"1More Skyforged",
"1More Void Zenith",
"1More Brawldog"
],
"BRB":["BRB",
"BRB Bewitching",
"BRB Brynn",
"BRB Daylight Star ☆ Magi",
"BRB Future Wave",
"BRB Goldforged",
"BRB Guild",
"BRB Honeybee",
"BRB Jörmungandr",
"BRB Mando & Grogu",
"BRB Master Of Night",
"BRB Mega Man & Rush",
"BRB Metadev",
"BRB Naoe",
"BRB Outhouse",
"BRB Prime",
"BRB Scuba",
"BRB Skyforged",
"BRB SpongeBob",
"BRB Thea",
"BRB Warthog",
"BRB X-wing"
],
"Cry":["Cry",
"Cry Caspian",
"Cry Deep Sea",
"Cry Goldforged",
"Cry Guild",
"Cry Haute Couture",
"Cry Headmaster",
"Cry Millennium Dragon",
"Cry Reindeer Games",
"Cry Skyforged",
"Cry Snowdrift",
"Cry The Covetous",
"Cry Ulgrim",
"Cry Corpse Bride"
],
"Facepalm":["Facepalm",
"Facepalm Brynn",
"Facepalm Ember",
"Facepalm Goldforged",
"Facepalm Guild",
"Facepalm Honor Bound",
"Facepalm Kern",
"Facepalm Lady Vera",
"Facepalm Metadev",
"Facepalm Obi-Wan",
"Facepalm Patrick",
"Facepalm Riptide",
"Facepalm Rising Dragon",
"Facepalm Shrek",
"Facepalm Skyforged",
"Facepalm Werebat"
],
"GG":["GG",
"GG Ahsoka",
"GG Corrupted Blood",
"GG Fangwild's Heart",
"GG Fenrir",
"GG Goldforged",
"GG Guild",
"GG Iroh",
"GG Jiro",
"GG Levi",
"GG Master Chief",
"GG Metadev",
"GG Owl Bard",
"GG Pinocchio",
"GG Ritzy",
"GG Sengoku Rappa",
"GG Skyforged",
"GG SpongeBob",
"GG Till Dawn"
],
"Heart":["Heart",
"Heart Ascendant",
"Heart Cheer Captain",
"Heart Date Night",
"Heart Demonkin",
"Heart Dragon",
"Heart Festive Yeti",
"Heart Goldforged",
"Heart Guild",
"Heart KO-rpse Candle",
"Heart Metadev",
"Heart Modern Monomi",
"Heart Nix",
"Heart Relentless Pest",
"Heart Rush",
"Heart Sea Krait",
"Heart Skyforged",
"Heart SpongeBob",
"Heart Yumiko"
],
"Laugh":["Laugh",
"Laugh Barbara",
"Laugh Equinox",
"Laugh Gardener",
"Laugh Goldforged",
"Laugh Gothic Chic",
"Laugh Guild",
"Laugh High Frequency",
"Laugh Holly Jolly",
"Laugh Horseman",
"Laugh Indomitable Daylight",
"Laugh Infernal Warlock",
"Laugh Jabba the Hutt",
"Laugh Munin",
"Laugh Nix Nervous",
"Laugh Obake",
"Laugh Palpatine",
"Laugh Skyforged",
"Laugh Termidex",
"Laugh Water Wars",
"Laugh Professor"
],
"LookinGood":["LookinGood",
"LookinGood Ascended",
"LookinGood Beachside",
"LookinGood Event Horizon",
"LookinGood Fait",
"LookinGood Famished Beast",
"LookinGood Globox",
"LookinGood Goldforged",
"LookinGood Guild",
"LookinGood Kay & Nix",
"LookinGood Octavius",
"LookinGood Roland",
"LookinGood Skyforged",
"LookinGood SpongeBob",
"LookinGood Swanky",
"LookinGood Three Blind Mice",
"LookinGood Rocker",
"LookinGood Reanimated"
],
"Rage":["Rage",
"Rage Akuma Shinobi Rage",
"Rage Azula",
"Rage Beastmaster",
"Rage Brute",
"Rage Chewbacca",
"Rage Cockatoo",
"Rage Darth Maul",
"Rage Diabolical Doll",
"Rage Fell Empress",
"Rage Goldforged",
"Rage Guild",
"Rage Honeybee",
"Rage Librarian",
"Rage Miracle Magi ☆ Starlit",
"Rage Petra",
"Rage Retro Reaper",
"Rage Skyforged",
"Rage Terror-Watt"
],
"RIP":["RIP",
"RIP Akuma no Kogo",
"RIP Aurora",
"RIP Caelestis",
"RIP Deathly Presence",
"RIP Goldforged",
"RIP Greedo",
"RIP Grunt",
"RIP Guild",
"RIP Interloper",
"RIP Metadev",
"RIP Nix",
"RIP Rayman",
"RIP Shinobi no Mono",
"RIP Skyforged",
"RIP Warborn"
],
"Shrug":["Shrug",
"Shrug Asuri",
"Shrug Detention",
"Shrug Dullahan",
"Shrug Goldforged",
"Shrug Guild",
"Shrug Han Solo",
"Shrug High Priestess",
"Shrug Hwarang",
"Shrug Netherworld",
"Shrug Skyforged",
"Shrug Sokka",
"Shrug Street Sovereign",
"Shrug Twilight Dragon",
"Shrug Vraxxy Jones",
"Shrug Xiaoyu"
],
"Smart":["Smart",
"Smart Cybernetic Beat",
"Smart Deathcap",
"Smart Dragon Hunter",
"Smart Elvenhollow",
"Smart Future Nokizaru",
"Smart Goldforged",
"Smart Guild",
"Smart Kazuya",
"Smart Krampus",
"Smart Luminous Paladin",
"Smart Mordex",
"Smart Shadow Dragon",
"Smart Skyforged",
"Smart Teatime",
"Smart The Monster"
],
"Sweat":["Sweat",
"Sweat C-3PO",
"Sweat Caspian",
"Sweat Dog Days",
"Sweat Fallen Prince",
"Sweat Goldforged",
"Sweat Guild",
"Sweat Kelpie",
"Sweat Koji",
"Sweat Leonidas",
"Sweat Red Rose",
"Sweat Sasha",
"Sweat Skyforged",
"Sweat Snowman",
"Sweat Soulbound",
"Sweat SpongeBob",
"Sweat Werewolf"
],
"Think":["Think",
"Think Anakin",
"Think Astral Core",
"Think Crimson Oni",
"Think Druid Mage",
"Think Elvenhollow",
"Think First Day",
"Think Goldforged",
"Think Guild",
"Think Metadev",
"Think Mirage",
"Think MonoKyle",
"Think Neostreet",
"Think Patrick",
"Think Red Romance",
"Think Santa",
"Think Skyforged",
"Think Vivi",
"Cth’ink"
],
"ThumbsDown":["ThumbsDown",
"ThumbsDown Colossal Titan",
"ThumbsDown Darth Vader",
"ThumbsDown Demon Bride",
"ThumbsDown Diamond Jack",
"ThumbsDown Diana",
"ThumbsDown Elvenhollow",
"ThumbsDown Goldforged",
"ThumbsDown Guild",
"ThumbsDown Heihachi",
"ThumbsDown Lord Farquaad",
"ThumbsDown Merrow",
"ThumbsDown Metadev",
"ThumbsDown Skyforged",
"ThumbsDown Usurper",
"ThumbsDown Vanir Guardian",
"ThumbsDown Zariel"
],
"ThumbsUp":["ThumbsUp",
"ThumbsUp Battle Droid",
"ThumbsUp Caster Kor",
"ThumbsUp Cu Sidhe",
"ThumbsUp Dog Days",
"ThumbsUp Goldforged",
"ThumbsUp Guild",
"ThumbsUp Jaeyun",
"ThumbsUp King",
"ThumbsUp Master Blacksmith",
"ThumbsUp Mega Man",
"ThumbsUp Metadev",
"ThumbsUp Puella Papilio",
"ThumbsUp Ray of the Dead",
"ThumbsUp Skyforged",
"ThumbsUp Star Commander",
"ThumbsUp Yasuke"
],
"Wait":["Wait",
"Wait Archfiend",
"Wait Ascended",
"Wait Cozy Sweater",
"Wait Date Night",
"Wait Fiona",
"Wait Goldforged",
"Wait Greased Lightning",
"Wait Green Thumb",
"Wait Guild",
"Wait Immortal",
"Wait Maitre d'",
"Wait Mecha Knight",
"Wait Octavius",
"Wait Skyforged",
"Wait The Betrayer",
"Wait Val"
],
"Wave":["Wave",
"Wave Cortana",
"Wave Goldforged",
"Wave Grogu",
"Wave Guild",
"Wave Katara",
"Wave Kuma",
"Wave Love Bug",
"Wave Metadev",
"Wave Obi-Wan",
"Wave Peacock",
"Wave Rayman",
"Wave Roll",
"Wave Royal Warrior",
"Wave Seven",
"Wave Skyforged",
"Wave Swim Team"
],
"Wow":["Wow",
"Wow Caster Thor",
"Wow Ehzot",
"Wow Ewok",
"Wow Fleeting Magi ☆ Starlit",
"Wow Goldforged",
"Wow Guild",
"Wow Hange",
"Wow Imugi",
"Wow Live Action",
"Wow Metadev",
"Wow Patrick",
"Wow Skyforged",
"Wow The Honorable",
"Wow The Seeker",
"Wow Xull",
"Wow Kindergarten"
],
"WP":["WP",
"WP 501st Clone Trooper",
"WP Arbiter",
"WP Armin",
"WP Cho-Kor-late",
"WP Elder Wild",
"WP Gentleman",
"WP Goldforged",
"WP Guild",
"WP Hattori",
"WP Modular Rift",
"WP Proto Man",
"WP Skyforged",
"WP Squidward",
"WP Suki",
"WP Sylvan Cleric",
"WP Tuxedo Bandit"
]},
    "weapons":
{
    "All":[],
    "sword":[],
    "hammer":[],
    "rocket lance":[],
    "blasters":[
"A Shot at Love",
"Ace of Spades",
"All Seeing Blasters",
"Aqua Blasters",
"Arts and Crafts",
"Asgardian Blasters",
"ASM Blasters",
"Asp and Adder",
"Aztlán Blasters",
"Bahian Blasters",
"Barnacle Blasters",
"Beautiful & Deadly",
"Big Dog Blasters",
"Birdshot",
"Blasters of Mercy",
"Blazing Deringers",
"Blazing Fire",
"Bolt Blasters",
"Boom Booms",
"Bowcaster & E-11 Blaster",
"Brimstone Blasters",
"Bubonic Blasters",
"Budding Blasters",
"Bullet Hail of the King",
"Candy Caliber",
"Cannonades",
"Catchand Release",
"Charmed, I'm Sure",
"Chicago Typewriters",
"Close Quarters",
"Commander and Chief",
"Crystalforged Blasters",
"Cyberlink Blasters",
"Cyber Myk Pistols",
"Dark Conjurers",
"Dark Elf Blasters",
"Darkheart Blasters",
"Darkshooters",
"Death Throes",
"Desequencers",
"Desert Island Blasters",
"Dessert Eagles",
"Destabilizers",
"Devil's Sight",
"Disassemblers",
"Disparo Sonoro",
"DL-44 Pistol & E-11 Blaster",
"Double Crossers",
"Double Dragons",
"Dragoon Flintlocks",
"Drakenfire",
"Dual Pistols",
"Dueling Pistols",
"Duty & Sacrifice",
"Dwarven-Forged Blasters",
"Ebon Blasters",
"Eclipsers",
"Electrode Guns",
"Emperor's Own Blasters",
"Equalizer",
"Exception Handlers",
"Exquisite Cannons",
"Fairy Fire",
"Fiendish Howl",
"Fire & Brimstone",
"Firewalls",
"Five-Sevens",
"Flight Risks",
"Flint-Lockers",
"Flintlock Claws",
"Forbidden Lamps",
"Galopante Blasts",
"Gemini's Wrath",
"Ghostand Goblin",
"Glimpse of Death",
"Glitz & Glam",
//"Golden Gears",
"Goldforged Blasters",
"Grisly Burrs",
"Guild Blasters",
"Guileless Hellfire Blasters",
"Hand Cannons",
"Hardlight Blasters",
"Hellhounds",
"Highwayman's Flintlocks",
"Hraesvelgr's Eyes",
"I B-94 Pistol & E-11 Blaster",
"Ice' Em",
"Jubilation Blasters",
"Juicy Carnage Shotguns",
"Jötunn Armaments",
"Ketchup & Mustard",
"Laser Blazers",
"Las Viudas",
"Lawbreakers",
"Lost Technology",
"Los Volcanes",
"Loves Me",
"M7 SMG & Plasma Rifle",
"Magnum Pistols",
"Maxilli-Blasts",
"Mega Buster",
"Mercy Killers",
"Moskitoes",
"Mother of Pearl Blasters",
"MP7s",
"Murder of Crows",
"Naughty & Nice",
"Needlers",
"Neo-City Blasters",
"Net Guns",
"Nightmare Witnesses",
"Nina's Blasters",
"Ninpō Unsealed Blasters",
"No Contest",
"Outbreak Perfected",
"Poppin’ TNTina",
"Powerplay Blasters",
"Protect & Serve",
"Purgeand Exorcise",
"Raycasters",
"Refractors",
"Repeating Crossbows",
"Revolvers",
"RGB Blasters",
"Rippleand Wave",
"Rose Gold Revolvers",
"Royal Family",
"Sacred Orders",
"Salty Shooters",
"Samaritans",
"Sawbones",
"Selenite Ray Guns",
"Shadow Casters",
"Sharkshooters",
"Shriek & Wail",
"Sidearms",
"Signal Flares",
"Silenced Pistols",
"Silverand Steel",
"Silver Bullets",
"Silver Sixshooters",
"Six ofa Kind",
"Sixshooters",
"Skyforged Blasters",
"Smokers Mk. B",
"Snake Eyes",
"Snow Shooters",
"Solar Flares",
"Soul Blasters",
"Space Shooters",
"Special Forces Pistols",
"Splish Splash",
"Standard Issue",
"Stardusters",
"Starved Scavengers",
"Tactical Pistols",
"Tactical Sidearms",
"Teacher's Pets",
"Tempoand Groove",
"The Consequences",
"The Doctor's Orders",
"The Hunters",
"The Neutralizers",
"The Roadhogs",
"The Sequels",
"The Singularities",
"Thunder Bass Blasters",
"Tide Turners",
"Toybox Pistol",
"Umbra Blasters",
"Valiant Armament Blasters",
"Vengeanceat Hand",
"Vespian Six Shooter",
"VM-19 Pistol & E-11 Blaster",
"Wheel Locks",
"Whirlwinds",
"Winged Danger",
"Wolf's Howl",
"Wurm Shooters",
"XLR8R's",
"Zhaktari Issue",
"Zipand Snap"
//"Venom Spitters",
//"Blaster Pistols",
],
    "spear":[],
    "katars":[],
    "axe":[],
    "bow":[],
    "gauntlets":[],
    "scythe":[],
    "cannon":[],
    "orb":[],
    "greatsword":[],
    "battle boots":[],
    "chakram":[
"All Seeing Chakram",
"Arcane Halo",
"Asgardian Chakram",
"Aztlán Chakram",
"Boon of Mars",
"Bug Fixer",
"Circle of Light",
"Clipeus Virtutis",
"Consecrate",
"Copy Cat",
"Crystalforged Chakram",
"Cyber Myk Chakram",
"Darkheart Chakram",
"Demon Art Kageshuriken",
"Dwarven-forged Chakram",
"Golden Order",
"Goldforged Chakram",
"Guild Chakram",
"Hardlight Chakram",
"Hringr of the Raven",
"Jade Maw",
"Jubilant Cymbal",
"Lethal Coil",
"Mercurial Reve",
"Neo-City Chakram",
"Nightmare Incisor",
"Ninpō Unsealed Chakram",
"Noxious Wheel",
"Penitence",
"Quantum War-Quoit",
"RGB Chakram",
"Scrollbar",
"Shield of the Empire",
"Skyforged Chakram",
"Stories of Antiquity",
"Sun Dust",
"Toybox Chakram",
"Umbra Chakram",
"Waning Crescents",
"Wheel of Thorns",
],
}
}
let list={};

function handleDocumentLoad() {
    const urlParams = new URLSearchParams(window.location.search);
    let param = urlParams.get('type');
    let subparam = urlParams.get('sub');
    var table = document.getElementById("table");
    if(param==""||param==null)
        for(let v in objdata)
            maketitle(v,table,urlParams,"");
    else if(param=="All")
        for(let v in objdata)
            maketable(v,table,urlParams,objdata,"");
    else if(param!=""&&subparam=="All"){
        list[param]={};
        for(let v in objdata[param])
            maketable(v,table,urlParams,objdata[param],param);
        }
    else if(param!=""&&objdata[param].length==null&&(subparam==""||subparam==null))
        for(let v in objdata[param])
            maketitle(v,table,urlParams,param);
    else if(param!=""&&subparam!=""){
        list[param]={};
        maketable(subparam,table,urlParams,objdata[param],param);}
    else if(objdata[param]==null){
        urlParams.set('type', "");urlParams.set('sub', "");
        window.location.search = urlParams.toString();
    }else
        maketable(param,table,urlParams,objdata,"");
}

function maketitle(v,defaulttable,urlParams,extra){
    let footer = document.createElement('footer');
    let title = document.createElement('h1');
    let img = document.createElement('img');
    let img2 = document.createElement('img');
    img.src="/assets/icons/"+v+"_icon.png";img2.src=img.src;
    img.className="img5";img2.className="img5";footer.className="footer2";
    footer.appendChild(img);footer.appendChild(title);footer.appendChild(img2);
    defaulttable.appendChild(footer);
    title.className="addselect";
    title.innerHTML=(extra=="")?v:(extra+": "+v);
    footer.addEventListener('click',()=>{
        if(extra==""){urlParams.set('type', v);urlParams.set('sub',"");}
        else{urlParams.set('type', extra);urlParams.set('sub', v);}
        window.location.search = urlParams.toString();});
}

function maketable(v,defaulttable,urlParams,objdata2,extra){
    maketitle(v,defaulttable,urlParams,extra);
    if(v!="All"){
        let table = document.createElement('footer');

    if(objdata2[v].length==null){
        list[v]={};
        for (let v2 in objdata2[v]){
            maketable(v2,defaulttable,urlParams,objdata2[v],v);
        }

    }else{

        if(extra=="")
            list[v]=getCookielist(v);
        else
            list[extra][v]=getCookielist(extra,v);
        defaulttable.appendChild(table);
        for (let i = 0; i < objdata2[v].length; i++)
            makeframe(v,table,i,objdata2,extra);
        }
    }
}

function makeframe(typename,table,i,objdata,extra){
    let cell = document.createElement('a');
    let img = document.createElement('div');
    let img2 = document.createElement('img');
    img.className="img4";
    img2.className="img1";
    img.id="img"+i+typename;
    cell.id="cell"+i+typename;
    let space = document.createElement('space');
    const tname=objdata[typename][i];
    img2.src="/assets/"+extra+"/"+typename+"/"+tname+".png";
    img2.addEventListener('error',function() {img2.src="/assets/other/not_found.png";});
    cell.className="cell";
    let name = document.createElement('text');
    name.innerHTML = tname;
    const type=gettype(tname);
    img.appendChild(img2);
    cell.appendChild(img);
    cell.appendChild(space);
    cell.appendChild(name);  
    table.appendChild(cell);
    if(type!=OWNINGTYPE.always&&type!=OWNINGTYPE.notown)
        cell.addEventListener('click',()=>movetrail(typename,i,type,extra));
    setback(i,type,typename,extra);
}

function gettype(typename){
    switch(typename){
        case "Brawler's Insignia":
        case "Default":
        case "Smoke N' Stars":
        case "Woohoo!":
        case "VALKRI Mk 1":
        case "Default Podium":
        case "Default Frame":
        case "1More": case "BRB": case "Cry": case "Facepalm": case "GG": case "Heart": case "Laugh": case "LookinGood": case "Rage": case "RIP": case "Shrug": case "Smart": case "Sweat": case "Think": case "ThumbsDown": case "ThumbsUp": case "Wait": case "Wave": case "Wow": case "WP":

        return OWNINGTYPE.always;

        case "Charmed, I'm Sure":case "Cyberlink Blasters":case "Death Throes":case "Hand Cannons":case "Hellhounds":case "Highwayman's Flintlocks":case "Los Volcanes":case "Selenite Ray Guns":case "Sidearms":case "Sixshooters":case "Vespian Six Shooter":case "Wheel Locks":
        
        case "Sun Dust":case "Quantum War-Quoit":case "Golden Order":case "Boon of Mars":
        

        case "Slow Clap":
        case "Roof Dance":
        return OWNINGTYPE.notown;
    }
    return OWNINGTYPE.buy;
}

function movetrail(typename,i,type,extra){
    if(extra!=""){
        list[extra][typename]=bitflip(list[extra][typename],i);
        addCookie(list[extra][typename],typename,extra);
    }else{
        list[typename]=bitflip(list[typename],i);
        addCookie(list[typename],null,typename);
    }
    setback(i,type,typename,extra);
}

function setback(i,type,typename,extra){
    var img = document.getElementById("img"+i+typename);
    var cell = document.getElementById("cell"+i+typename);
    setherocolorccc(img,cell,bitget(((extra=="")?list[typename]:((list[extra]==null)?[]:list[extra][typename])),i),type);
}